import { TypographyOptions } from '@mui/material/styles/createTypography';

export const textTheme: TypographyOptions = {
  displayLarge: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '57px',
    lineHeight: '64px',
    letterSpacing: '0px',
  },
  displayMedium: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '45px',
    lineHeight: '52px',
    letterSpacing: '0px',
  },
  displaySmall: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '36px',
    lineHeight: '44px',
    letterSpacing: '0px',
  },
  headlineLarge: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '32px',
    lineHeight: '40px',
    letterSpacing: '0px',
  },
  headlineMedium: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '28px',
    lineHeight: '36px',
    letterSpacing: '0px',
  },
  headlineSmall: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '24px',
    lineHeight: '32px',
    letterSpacing: '0px',
  },
  titleLarge: {
    fontFamily: 'Roboto',
    fontSize: '22px',
    lineHeight: '28px',
    letterSpacing: '0px',
  },
  titleMedium: {
    fontFamily: 'Roboto',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '0.15px',
  },
  titleSmall: {
    fontFamily: 'Roboto',
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: '0.1px',
  },
  labelLarge: {
    fontFamily: 'Roboto',
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: '0.1px',
  },
  labelMedium: {
    fontFamily: 'Roboto',
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '0.5px',
  },
  labelSmall: {
    fontFamily: 'Roboto',
    fontSize: '11px',
    lineHeight: '16px',
    letterSpacing: '0.5px',
  },
  bodyLarge: {
    fontFamily: 'Roboto',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '0.5px',
  },
  bodyMedium: {
    fontFamily: 'Roboto',
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: '0.25px',
  },
  bodySmall: {
    fontFamily: 'Roboto',
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '0.4px',
  },
};
